# Dockerfile for AWS ECS deployment
FROM python:3.11

# init
RUN mkdir -p /app
RUN touch /app/__init__.py

# create workspace
WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# RUN cat /app/main.py

# start uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

